name: CI
on: 
  push:
    paths-ignore:
      - '.github/templates/**'
      - 'README.md'
  pull_request:
    types: [opened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build
        run: gradle build --info
      
      - name: Copy
        run: |
          mkdir archive
          mv measure-*/target/measure-*.jar archive

      - name: Archive
        uses: actions/upload-artifact@v1
        with:
          name: jmeasure
          path: archive