name: CI
on: 
  push:
    paths-ignore:
      - '.github/templates/**'
      - 'README.md'
  pull_request:
    types: [opened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: openjdk:8
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: ./gradlew build --info